import React from 'react';

export default function Donatello() {
  return (
    <div className="componentWrapper">
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
      </div>
      <div className="donatello wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="ninjaTurtlePurple"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donatello wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
