import React from "react";

export default function Donatello() {
  return (
    <div class="mb">
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
      </div>
      <div class="donatello wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="ninjaTurtlePurple"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="donatello wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
