import React from "react";

export default function Leonardo() {
  return (
    <div class="mb">
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="ninjaTurtleBlue"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="leonardo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
