import React from "react";

export default function Michelangelo() {
  return (
    <div class="mb">
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="ninjaTurtleOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="ninjaTurtleRed"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="ninjaTurtleGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="michelangelo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
