import React from 'react';

export default function Michelangelo() {
  return (
    <div className="mb">
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="ninjaTurtleOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="michelangelo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
