import React from 'react';

export default function Raphael() {
  return (
    <div className="componentWrapper">
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
      </div>
      <div className="raphael wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="ninjaTurtleRed"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="ninjaTurtleGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="raphael wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
