export default function AdventureTime() {
  return (
    <div className="componentWrapper">
      <div className="adventureTime wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="adventureTime"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="adventureTime wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
