import React from 'react';

export default function Garfield() {
  return (
    <div className="mb">
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldPink"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldPink"></div>
        <div className="garfieldPink"></div>
        <div className="garfieldPink"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldYellow"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldOrange"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="garfield wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="garfieldBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
