import React from 'react';

export default function GeorgeCostanza() {
  return (
    <div className="componentWrapper">
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeHair"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeHair"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeEyes"></div>
        <div className="georgeEyes"></div>
        <div className="black"></div>
        <div className="georgeEyes"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeHair"></div>
        <div className="georgeSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeEyes"></div>
        <div className="georgeEyes"></div>
        <div className="georgeSkin"></div>
        <div className="georgeEyes"></div>
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin"></div>
        <div className="white"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeShirtGrey"></div>
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeShirtGrey"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtGrey"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtGrey"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtGrey"></div>
        <div className="georgeDarkGreen"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeDarkGreen"></div>
        <div className="white"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeDarkGreen"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtGrey"></div>
        <div className="georgeLightGreen"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtGrey"></div>
        <div className="georgeLightGreen"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeLightGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeShirtYellow"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtGrey"></div>
        <div className="white"></div>
        <div className="georgeLightGreen"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeShirtGrey"></div>
        <div className="white"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeSkin2"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeDarkGreen"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin"></div>
        <div className="georgeSkin2"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeBeltBuckle"></div>
        <div className="georgeBeltBuckle"></div>
        <div className="georgeBeltBuckle"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="georgeSkin2"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgePantsOutline"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePantsOutline"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgePantsOutline"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePantsOutline"></div>
        <div className="georgePantsOutline"></div>
        <div className="georgePantsOutline"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePantsOutline"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="georgePantsOutline"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePantsOutline"></div>
        <div className="white"></div>
        <div className="georgePantsOutline"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePants"></div>
        <div className="georgePantsOutline"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="white"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="white"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="white"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="white"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="white"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
        <div className="georgeShoes"></div>
      </div>
      <div className="george wrapper">
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="white"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
        <div className="georgeHair"></div>
      </div>
    </div>
  );
}
