import React from "react";

export default function GeorgeCostanza() {
  return (
    <div class="mb">
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeHair"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeHair"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeEyes"></div>
        <div class="georgeEyes"></div>
        <div class="black"></div>
        <div class="georgeEyes"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeHair"></div>
        <div class="georgeSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeEyes"></div>
        <div class="georgeEyes"></div>
        <div class="georgeSkin"></div>
        <div class="georgeEyes"></div>
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin"></div>
        <div class="white"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeShirtGrey"></div>
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeShirtGrey"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtGrey"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtGrey"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtGrey"></div>
        <div class="georgeDarkGreen"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeDarkGreen"></div>
        <div class="white"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeDarkGreen"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtGrey"></div>
        <div class="georgeLightGreen"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtGrey"></div>
        <div class="georgeLightGreen"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeLightGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeShirtYellow"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtGrey"></div>
        <div class="white"></div>
        <div class="georgeLightGreen"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeShirtGrey"></div>
        <div class="white"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeSkin2"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeDarkGreen"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin"></div>
        <div class="georgeSkin2"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeBeltBuckle"></div>
        <div class="georgeBeltBuckle"></div>
        <div class="georgeBeltBuckle"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="georgeSkin2"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgePantsOutline"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePantsOutline"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgePantsOutline"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePantsOutline"></div>
        <div class="georgePantsOutline"></div>
        <div class="georgePantsOutline"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePantsOutline"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="georgePantsOutline"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePantsOutline"></div>
        <div class="white"></div>
        <div class="georgePantsOutline"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePants"></div>
        <div class="georgePantsOutline"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="white"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="white"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="white"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="white"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="white"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
        <div class="georgeShoes"></div>
      </div>
      <div class="george wrapper">
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="white"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
        <div class="georgeHair"></div>
      </div>
    </div>
  );
}
