import React from 'react';

export default function KlayThompson() {
  return (
    <div className="componentWrapper">
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
      </div>
      <div className="klay wrapper">
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
      </div>
      <div className="klay wrapper">
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="basketball"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="warriorsBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="klaySkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klayShoes"></div>
        <div className="warriorsGold"></div>
        <div className="klayShoes"></div>
        <div className="klayShoes"></div>
        <div className="white"></div>
        <div className="warriorsGold"></div>
        <div className="klayShoes"></div>
        <div className="klayShoes"></div>
        <div className="warriorsGold"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="klayShoes"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="white"></div>
        <div className="klayShoes"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="klayShoes"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="klayShoes"></div>
        <div className="klayShoes"></div>
        <div className="warriorsGold"></div>
        <div className="white"></div>
        <div className="warriorsGold"></div>
        <div className="klayShoes"></div>
        <div className="klayShoes"></div>
        <div className="klayShoes"></div>
        <div className="klayShoes"></div>
        <div className="klayShoes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="klay wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="warriorsGold"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
