import React from 'react';

export default function MineCraftCreeper() {
  return (
    <div className="componentWrapper">
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
      </div>
      <div className="creeper wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
      </div>
      <div className="creeper wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="creeper"></div>
        <div className="creeper"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="creeper wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
