export default function MineCraftSteve() {
  return (
    <div className="componentWrapper">
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="steveHair"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveHair"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveHair"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveSkin"></div>
        <div className="white"></div>
        <div className="steveEyes"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveEyes"></div>
        <div className="white"></div>
        <div className="steveSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveNose"></div>
        <div className="steveNose"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveMouth"></div>
        <div className="steveMouth"></div>
        <div className="steveMouth"></div>
        <div className="steveMouth"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants2"></div>
        <div className="steveShirt"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants2"></div>
        <div className="steveShirt"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
        <div className="steveSkin"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="stevePants"></div>
        <div className="stevePants2"></div>
        <div className="stevePants2"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants2"></div>
        <div className="stevePants2"></div>
        <div className="stevePants"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="stevePants"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="steve wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="steveShoes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
