import React from "react";

export default function MineCraftSteve() {
  return (
    <div class="mb">
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="steveHair"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveHair"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveHair"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveSkin"></div>
        <div class="white"></div>
        <div class="steveEyes"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveEyes"></div>
        <div class="white"></div>
        <div class="steveSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveNose"></div>
        <div class="steveNose"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveMouth"></div>
        <div class="steveMouth"></div>
        <div class="steveMouth"></div>
        <div class="steveMouth"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants2"></div>
        <div class="steveShirt"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants2"></div>
        <div class="steveShirt"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
        <div class="steveSkin"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="stevePants"></div>
        <div class="stevePants2"></div>
        <div class="stevePants2"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants2"></div>
        <div class="stevePants2"></div>
        <div class="stevePants"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="stevePants"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="steve wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="steveShoes"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
