import React from "react";

export default function MineCraftCreeper() {
  return (
    <div class="mb">
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
      </div>
      <div class="creeper wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
      </div>
      <div class="creeper wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="creeper"></div>
        <div class="creeper"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="creeper wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
