export default function Pacman() {
  return (
    <div className="componentWrapper">
      <div className="pacmanGhost wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="white"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="pacmanGhostBlue"></div>
        <div className="white"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="pacmanGhostRed"></div>
        <div className="black"></div>
      </div>
      <div className="pacmanGhost wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
    </div>
  );
}
