import React from 'react';

export default function Rick() {
  return (
    <div className="componentWrapper">
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="rickSkin"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rickSkin"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickHair"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickHair"></div>
        <div className="rickHair"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="ghostRed"></div>
        <div className="ghostRed"></div>
        <div className="ghostRed"></div>
        <div className="rickSkin"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickSkin"></div>
        <div className="rickSkin"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="rickShirt"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="marioYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="rickPants"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickShirt"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="rickShirt"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickSkin"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="rickSkin"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="rickPants"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickPants"></div>
        <div className="greyBackground"></div>
        <div className="rickPants"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickPants"></div>
        <div className="greyBackground"></div>
        <div className="rickPants"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickShirt"></div>
        <div className="greyBackground"></div>
        <div className="rickShirt"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="rick wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="rickShoes"></div>
        <div className="rickShoes"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
    </div>
  );
}
