import React from 'react';

export default function Rick() {
  return (
    <div class="mb">
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="rickSkin"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rickSkin"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickHair"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickHair"></div>
        <div class="rickHair"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="ghostRed"></div>
        <div class="ghostRed"></div>
        <div class="ghostRed"></div>
        <div class="rickSkin"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickSkin"></div>
        <div class="rickSkin"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="rickShirt"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="marioYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="rickPants"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickShirt"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="rickShirt"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickSkin"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="rickSkin"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="rickPants"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickPants"></div>
        <div class="greyBackground"></div>
        <div class="rickPants"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickPants"></div>
        <div class="greyBackground"></div>
        <div class="rickPants"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickShirt"></div>
        <div class="greyBackground"></div>
        <div class="rickShirt"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="rick wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="rickShoes"></div>
        <div class="rickShoes"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
    </div>
  );
}
