import React from 'react';

export default function Ryu() {
  return (
    <div className="mb">
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="ryuRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="ryuRed"></div>
        <div className="greyBackground"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="ryuRed"></div>
        <div className="greyBackground"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="ryuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
      </div>
      <div className="ryu wrapper">
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuRed"></div>
      </div>
      <div className="ryu wrapper">
        <div className="ryuRed"></div>
        <div className="ryuRed"></div>
        <div className="ryuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="greyBackground"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="greyBackground"></div>
      </div>
      <div className="ryu wrapper">
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="greyBackground"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
        <div className="ryuBeige"></div>
      </div>
    </div>
  );
}
