import React from 'react';

export default function Ryu() {
  return (
    <div class="mb">
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="ryuRed"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="ryuRed"></div>
        <div class="greyBackground"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="ryuRed"></div>
        <div class="greyBackground"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="ryuBeige"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
      </div>
      <div class="ryu wrapper">
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuRed"></div>
      </div>
      <div class="ryu wrapper">
        <div class="ryuRed"></div>
        <div class="ryuRed"></div>
        <div class="ryuBeige"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="greyBackground"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="greyBackground"></div>
      </div>
      <div class="ryu wrapper">
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="greyBackground"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
        <div class="ryuBeige"></div>
      </div>
    </div>
  );
}
