import React from 'react';

export default function Waldo() {
  return (
    <div className="componentWrapper">
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="waldoBeige"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="waldoBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="waldoBeige"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="waldoRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="waldo wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
    </div>
  );
}
