import React from "react";

export default function Waldo() {
  return (
    <div class="mb">
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="waldoBeige"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="waldoBeige"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="waldoBeige"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="waldoRed"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="waldo wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
      </div>
    </div>
  );
}
