import React from 'react';

export default function DonaldDuck() {
  return (
    <div className="mb">
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="donaldHat"></div>
        <div className="donaldHat"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="donaldEyes"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="donaldEyes"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="donaldBeak"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldMouth"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldTongue"></div>
        <div className="donaldTongue"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldBeak"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldTongue"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldBeak"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldBeak"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldMouth"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="donaldDuck wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="donaldBeak"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
