export default function Pluto() {
  return (
    <div className="componentWrapper">
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
      </div>
      <div className="pluto wrapper">
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="plutoRed"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="plutoYellow"></div>
        <div className="plutoYellow"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="pluto wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="plutoRed"></div>
        <div className="plutoRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
