export default function WallE() {
  return (
    <div className="componentWrapper">
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="wallEGreen"></div>
        <div className="wallEGreen2"></div>
        <div className="wallELightGrey"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="wallEOrange"></div>
        <div className="wallEOrange"></div>
        <div className="wallEOrange"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="wallEOrange"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallEOrange"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="wallE wrapper">
        <div className="black"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallELightGrey"></div>
        <div className="black"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="black"></div>
      </div>
      <div className="wallE wrapper">
        <div className="black"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="wallEDarkGrey"></div>
        <div className="wallEDarkGrey"></div>
        <div className="black"></div>
      </div>
      <div className="wallE wrapper">
        <div className="black"></div>
        <div className="walLEDarkGrey"></div>
        <div className="walLEDarkGrey"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="walLEDarkGrey"></div>
        <div className="walLEDarkGrey"></div>
        <div className="black"></div>
      </div>
      <div className="wallE wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
      </div>
    </div>
  );
}
