export default function Zazu() {
  return (
    <div className="componentWrapper">
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="zazuBlue"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="zazuBeige"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuBlue"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="zazuBlue"></div>
        <div className="zazuYellow"></div>
        <div className="zazuYellow"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuYellow"></div>
        <div className="zazuYellow"></div>
        <div className="zazuYellow"></div>
        <div className="zazuYellow"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuRed"></div>
        <div className="zazuRed"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="zazuBlue"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="zazuBeige"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuOrange"></div>
        <div className="zazuOrange"></div>
        <div className="zazuOrange"></div>
        <div className="white"></div>
        <div className="zazuOrange"></div>
        <div className="zazuOrange"></div>
        <div className="zazuOrange"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="zazu wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuOrange"></div>
        <div className="zazuOrange"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="zazuOrange"></div>
        <div className="zazuOrange"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
