import React from 'react';

export default function BananaPeel() {
  return (
    <div className="componentWrapper">
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
      </div>
      <div className="banana wrapper">
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="bananaYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="banana wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
