import React from "react";

export default function Flower() {
  return (
    <div class="mb">
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
      </div>
      <div class="flower wrapper">
        <div class="black"></div>
        <div class="flowerRed"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
      </div>
      <div class="flower wrapper">
        <div class="black"></div>
        <div class="flowerRed"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
      </div>
      <div class="flower wrapper">
        <div class="black"></div>
        <div class="flowerRed"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerRed"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerRed"></div>
        <div class="flowerRed"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="flowerOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="flowerRed"></div>
        <div class="flowerRed"></div>
        <div class="flowerRed"></div>
        <div class="flowerRed"></div>
        <div class="flowerRed"></div>
        <div class="flowerRed"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
      </div>
      <div class="flower wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerDarkGreen"></div>
        <div class="flowerLightGreen"></div>
        <div class="black"></div>
      </div>
    </div>
  );
}
