import React from 'react';

export default function Flower() {
  return (
    <div className="mb">
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
      </div>
      <div className="flower wrapper">
        <div className="black"></div>
        <div className="flowerRed"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
      </div>
      <div className="flower wrapper">
        <div className="black"></div>
        <div className="flowerRed"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
      </div>
      <div className="flower wrapper">
        <div className="black"></div>
        <div className="flowerRed"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerRed"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerRed"></div>
        <div className="flowerRed"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="flowerOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="flowerRed"></div>
        <div className="flowerRed"></div>
        <div className="flowerRed"></div>
        <div className="flowerRed"></div>
        <div className="flowerRed"></div>
        <div className="flowerRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
      </div>
      <div className="flower wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerDarkGreen"></div>
        <div className="flowerLightGreen"></div>
        <div className="black"></div>
      </div>
    </div>
  );
}
