import React from 'react';

export default function Goomba() {
  return (
    <div className="componentWrapper">
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
      </div>
      <div className="goomba wrapper">
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
      </div>
      <div className="goomba wrapper">
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
      </div>
      <div className="goomba wrapper">
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaLightBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
      </div>
      <div className="goomba wrapper">
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
        <div className="goombaBrown"></div>
      </div>
    </div>
  );
}
