import React from "react";

export default function Koopa() {
  return (
    <div class="mb">
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="koopaGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="koopaOrange"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="koopa wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
