import React from 'react';

export default function Koopa() {
  return (
    <div className="mb">
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="koopaGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="koopaOrange"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="koopa wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
