import React from 'react';

export default function Mariofrog() {
  return (
    <div className="componentWrapper">
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="black"></div>
        <div className="marioFrog"></div>
        <div className="marioFrog"></div>
        <div className="black"></div>
        <div className="marioFrog"></div>
        <div className="black"></div>
        <div className="marioFrog"></div>
        <div className="marioFrog"></div>
        <div className="marioFrog"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="frogMario"></div>
        <div className="black"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="marioSkin"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="frogMario wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
