import React from "react";

export default function Mariofrog() {
  return (
    <div class="mb">
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="black"></div>
        <div class="marioFrog"></div>
        <div class="marioFrog"></div>
        <div class="black"></div>
        <div class="marioFrog"></div>
        <div class="black"></div>
        <div class="marioFrog"></div>
        <div class="marioFrog"></div>
        <div class="marioFrog"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="frogMario"></div>
        <div class="black"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="marioSkin"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="frogMario wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
