import React from "react";

export default function Mushroom() {
  return (
    <div class="mb">
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="black"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="black"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="black"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="black"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="black"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="black"></div>
        <div class="white"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="mushroomRed"></div>
        <div class="black"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="mushroom wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
