export default function Mushroom() {
  return (
    <div className="componentWrapper">
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="black"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="black"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="black"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="black"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="black"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="black"></div>
        <div className="white"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="mushroomRed"></div>
        <div className="black"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="mushroom wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
