import React from "react";

export default function RainbowStar() {
  return (
    <div class="mb">
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowRed"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="black"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="black"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="black"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowIndigo"></div>
        <div class="black"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowRed"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="black"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowGreen"></div>
        <div class="black"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowIndigo"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowYellow"></div>
        <div class="black"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="black"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowIndigo"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowOrange"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowIndigo"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowIndigo"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowIndigo"></div>
        <div class="rainbowIndigo"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowYellow"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowBlue"></div>
        <div class="rainbowIndigo"></div>
        <div class="rainbowIndigo"></div>
        <div class="rainbowIndigo"></div>
        <div class="rainbowViolet"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowBlue"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="rainbowIndigo"></div>
        <div class="rainbowIndigo"></div>
        <div class="rainbowViolet"></div>
        <div class="rainbowViolet"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="rainbowViolet"></div>
        <div class="rainbowViolet"></div>
        <div class="rainbowViolet2"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowGreen"></div>
        <div class="rainbowGreen"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="rainbowViolet2"></div>
        <div class="rainbowViolet2"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="rainbowStar wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
    </div>
  );
}
