import React from 'react';

export default function RainbowStar() {
  return (
    <div className="componentWrapper">
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowRed"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="black"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="black"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="black"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowIndigo"></div>
        <div className="black"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowRed"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="black"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowGreen"></div>
        <div className="black"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowIndigo"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowYellow"></div>
        <div className="black"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="black"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowIndigo"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowOrange"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowIndigo"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowIndigo"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowIndigo"></div>
        <div className="rainbowIndigo"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowYellow"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowBlue"></div>
        <div className="rainbowIndigo"></div>
        <div className="rainbowIndigo"></div>
        <div className="rainbowIndigo"></div>
        <div className="rainbowViolet"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowBlue"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="rainbowIndigo"></div>
        <div className="rainbowIndigo"></div>
        <div className="rainbowViolet"></div>
        <div className="rainbowViolet"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="rainbowViolet"></div>
        <div className="rainbowViolet"></div>
        <div className="rainbowViolet2"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowGreen"></div>
        <div className="rainbowGreen"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="rainbowViolet2"></div>
        <div className="rainbowViolet2"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="rainbowStar wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
    </div>
  );
}
