import React from "react";

export default function TriForce() {
  return (
    <div class="mb">
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="white"></div>
      </div>
      <div class="triforce wrapper">
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="triforceYellow"></div>
        <div class="black"></div>
      </div>
      <div class="triforce wrapper">
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
        <div class="black"></div>
      </div>
    </div>
  );
}
