import React from 'react';

export default function TriForce() {
  return (
    <div className="mb">
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="white"></div>
      </div>
      <div className="triforce wrapper">
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="triforceYellow"></div>
        <div className="black"></div>
      </div>
      <div className="triforce wrapper">
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
        <div className="black"></div>
      </div>
    </div>
  );
}
